from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.ai.service import AIService
from app.core.logging import get_logger
from app.models import (
    AnalysisJob,
    Document,
    DriftFinding,
    FindingStatus,
    GeneratedPR,
    GitHubInstallation,
    Repository,
)
from app.services.analysis.docfix import generate_updated_document
from app.services.github.client import GitHubClient

logger = get_logger("variorum.doc_pr")


@dataclass
class DocFixResult:
    generated_pr_id: int
    pr_number: int | None
    branch: str
    url: str | None
    reused: bool = False


def _branch_name(finding_id: int) -> str:
    return f"variorum/doc-fix-{finding_id}"


def _pr_body(finding: DriftFinding, evidence: dict) -> str:
    lines = [
        "This pull request was generated by **Variorum** to keep documentation in "
        "sync with code changes. Please review carefully before merging.",
        "",
        f"**Drift detected:** {finding.summary}",
    ]
    pr_number = evidence.get("pr_number")
    if pr_number:
        lines.append(f"**Triggered by:** #{pr_number}")
    drift_evidence = evidence.get("drift_evidence") or []
    if drift_evidence:
        lines.append("")
        lines.append("**Evidence:**")
        lines.extend(f"- {item}" for item in drift_evidence)
    provider = evidence.get("provider")
    if provider:
        lines.append("")
        lines.append(f"_Assessed via {provider} ({evidence.get('model', 'unknown model')})._")
    return "\n".join(lines)


async def create_doc_fix_pr(
    db: Session,
    finding: DriftFinding,
    *,
    client: GitHubClient,
    ai: AIService,
) -> DocFixResult | None:
    """Generate an updated document and open a pull request for a drift finding.
    Idempotent per finding. Returns None if there is nothing to change."""
    existing = db.execute(
        select(GeneratedPR).where(GeneratedPR.drift_finding_id == finding.id)
    ).scalar_one_or_none()
    if existing is not None:
        return DocFixResult(existing.id, existing.pr_number, existing.branch, existing.url, True)

    document = db.get(Document, finding.document_id) if finding.document_id else None
    if document is None:
        return None
    job = db.get(AnalysisJob, finding.analysis_job_id)
    repo = db.get(Repository, job.repository_id) if job else None
    if repo is None:
        return None
    installation = db.get(GitHubInstallation, repo.installation_id)
    if installation is None:
        return None

    inst_id = installation.installation_id
    base = repo.default_branch
    current, blob_sha = await client.get_file(inst_id, repo.full_name, document.path, base)
    if current is None:
        logger.info("doc-fix skipped: %s not present on %s", document.path, base)
        return None

    evidence = finding.evidence or {}
    new_content = await generate_updated_document(
        ai,
        doc_path=document.path,
        current_content=current,
        drift_summary=finding.summary,
        suggested_update=evidence.get("suggested_update"),
        evidence=evidence.get("drift_evidence") or [],
    )
    if not new_content.strip() or new_content.strip() == current.strip():
        logger.info("doc-fix produced no change for %s", document.path)
        return None

    branch = _branch_name(finding.id)
    base_sha = await client.get_branch_sha(inst_id, repo.full_name, base)
    await client.create_branch(inst_id, repo.full_name, branch, base_sha)
    await client.put_file(
        inst_id,
        repo.full_name,
        document.path,
        f"docs: update {document.path} to match code changes",
        new_content,
        branch,
        blob_sha,
    )
    pr = await client.create_pull_request(
        inst_id,
        repo.full_name,
        title=f"Update {document.path} to match code changes",
        head=branch,
        base=base,
        body=_pr_body(finding, evidence),
    )

    generated = GeneratedPR(
        drift_finding_id=finding.id,
        repository_id=repo.id,
        pr_number=pr.number,
        branch=branch,
        url=pr.url,
        state="open",
    )
    db.add(generated)
    finding.status = FindingStatus.pr_opened
    db.commit()
    db.refresh(generated)
    logger.info("doc-fix PR opened repo=%s pr=%s branch=%s", repo.full_name, pr.number, branch)
    return DocFixResult(generated.id, pr.number, branch, pr.url)
