from __future__ import annotations

import httpx
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.ai.service import AIService
from app.core.logging import get_logger
from app.models import AnalysisJob, GeneratedPR, GitHubInstallation, Repository, RiskFinding
from app.services.analysis.doc_pr import DocFixResult
from app.services.analysis.testgen import generate_test_file, test_path_for
from app.services.github.client import GitHubClient
from app.services.indexer.languages import spec_for_path

logger = get_logger("variorum.test_pr")


def _branch_name(finding_id: int) -> str:
    return f"variorum/tests-{finding_id}"


def _pr_body(finding: RiskFinding) -> str:
    evidence = finding.evidence or {}
    lines = [
        "This pull request was generated by **Variorum** to add test coverage for "
        "a change flagged as risky. Review carefully — generated tests are a "
        "starting point and must pass your CI before merging.",
        "",
        f"**Risk ({finding.risk_level.value}):** {finding.summary}",
        f"**File:** `{finding.path}`",
    ]
    pr_number = evidence.get("pr_number")
    if pr_number:
        lines.append(f"**Triggered by:** #{pr_number}")
    scenarios = evidence.get("untested_scenarios") or []
    if scenarios:
        lines.append("")
        lines.append("**Scenarios covered:**")
        lines.extend(f"- {s}" for s in scenarios)
    return "\n".join(lines)


async def create_test_pr(
    db: Session,
    finding: RiskFinding,
    *,
    client: GitHubClient,
    ai: AIService,
) -> DocFixResult | None:
    """Generate a test file for a risk finding's source file and open a PR.
    Idempotent per finding; returns None if nothing could be generated."""
    existing = db.execute(
        select(GeneratedPR).where(GeneratedPR.risk_finding_id == finding.id)
    ).scalar_one_or_none()
    if existing is not None:
        return DocFixResult(existing.id, existing.pr_number, existing.branch, existing.url, True)

    job = db.get(AnalysisJob, finding.analysis_job_id)
    repo = db.get(Repository, job.repository_id) if job else None
    if repo is None:
        return None
    installation = db.get(GitHubInstallation, repo.installation_id)
    if installation is None:
        return None

    inst_id = installation.installation_id
    base = repo.default_branch
    spec = spec_for_path(finding.path)
    language = spec.name if spec else "text"

    source, _sha = await client.get_file(inst_id, repo.full_name, finding.path, base)
    if source is None:
        logger.info("test-gen skipped: %s not present on %s", finding.path, base)
        return None

    test_content = await generate_test_file(
        ai,
        source_path=finding.path,
        source_content=source,
        untested_scenarios=(finding.evidence or {}).get("untested_scenarios") or [],
        language=language,
    )
    if not test_content.strip():
        return None

    test_path = test_path_for(finding.path, language)
    branch = _branch_name(finding.id)
    base_sha = await client.get_branch_sha(inst_id, repo.full_name, base)
    await client.create_branch(inst_id, repo.full_name, branch, base_sha)
    _, existing_sha = await client.get_file(inst_id, repo.full_name, test_path, branch)
    await client.put_file(
        inst_id,
        repo.full_name,
        test_path,
        f"test: add generated tests for {finding.path}",
        test_content,
        branch,
        existing_sha,
    )
    try:
        pr = await client.create_pull_request(
            inst_id,
            repo.full_name,
            title=f"Add tests for {finding.path}",
            head=branch,
            base=base,
            body=_pr_body(finding),
        )
    except httpx.HTTPStatusError as exc:
        if exc.response.status_code != 422:
            raise
        existing_pr = await client.find_open_pull_request(inst_id, repo.full_name, branch)
        if existing_pr is None:
            raise
        pr = existing_pr

    generated = GeneratedPR(
        risk_finding_id=finding.id,
        repository_id=repo.id,
        pr_number=pr.number,
        branch=branch,
        url=pr.url,
        state="open",
    )
    db.add(generated)
    db.commit()
    db.refresh(generated)
    logger.info("test PR opened repo=%s pr=%s file=%s", repo.full_name, pr.number, finding.path)
    return DocFixResult(generated.id, pr.number, branch, pr.url)
