"""add knowledge_entries

Revision ID: 00a46f90c915
Revises: d38ed28814ea
Create Date: 2026-07-26 16:54:50.043247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '00a46f90c915'
down_revision: Union[str, None] = 'd38ed28814ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('commit', 'pull_request', 'issue', 'review', name='knowledgekind'), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repository_id', 'kind', 'source_ref', name='uq_knowledge_repo_kind_ref')
    )
    op.create_index(op.f('ix_knowledge_entries_repository_id'), 'knowledge_entries', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_entries_repository_id'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    # ### end Alembic commands ###
