"""add risk_findings

Revision ID: 207ea974cf8d
Revises: 811a96b28f2a
Create Date: 2026-07-26 17:42:15.353391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '207ea974cf8d'
down_revision: Union[str, None] = '811a96b28f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_job_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('risk_level', postgresql.ENUM('info', 'low', 'medium', 'high', name='driftseverity', create_type=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_findings_analysis_job_id'), 'risk_findings', ['analysis_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_findings_analysis_job_id'), table_name='risk_findings')
    op.drop_table('risk_findings')
    # ### end Alembic commands ###
