"""knowledge embedding column

Revision ID: 811a96b28f2a
Revises: a70dd0fb5bba
Create Date: 2026-07-26 17:24:16.147500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '811a96b28f2a'
down_revision: Union[str, None] = 'a70dd0fb5bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_entries', sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_knowledge_entries_fts', table_name='knowledge_entries', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_entries_fts', 'knowledge_entries', [sa.text("to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(body, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_column('knowledge_entries', 'embedding')
    # ### end Alembic commands ###
